error:
  code:
    unauthorized: 401
    forbidden: 403
    internal_error: 500
    bad_request: 400
    no_device_found: 204
    incorrect_device_count: 204
    no_algosec_enabled_device_found: 204
    no_algosec_actionable_work_found: 204
  message:
    unauthorized: Unauthorised
    forbidden: Forbidden
    internal_error: Internal Error
    invalid_pcr_change_request_details: Invalid JSON Input
    no_device_found: Not Found
    incorrect_device_count: Incorrect Count
    no_algosec_enabled_device_found: No Content
    no_algosec_actionable_work_found: No Content
    invalid_policy_update_source: Could not resolve source
    invalid_policy_update_destination: Could not resolve destination
    invalid_port: Invalid Port
    invalid_protocol: Invalid Protocol
  http_status:
    unauthorized: 401
    forbidden: 403
    internal_error: 500
    bad_request: 400
    no_device_found: 204
    incorrect_device_count: 204
    no_algosec_enabled_device_found: 204
    no_algosec_actionable_work_found: 204
app:
  service:
    url:
      algosec_fireflow_authentication_url: test_url1
      algosec_fireflow_change_request_url: test_url2
      device_enablement_values_url: test_url3
      device_url_with_hostname: test_url4
      device_mapping_url: test_url5
      find_network_objects_by_device_name: test_url6
      find_service_objects_by_remdedy_device_id:: test_url7
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
server:
  port: 3333
spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
algosec-integration-ms:
  mss-datasource:
    jdbc-url: jdbc:h2:~/test;AUTO_SERVER=TRUE
cleanup_threshold_hours: 24
network_protocol_list: TCP,UDP,ICMP,tcp,udp,icmp
policy_update_request_template: SOC Standard Request Template
policy_rule_removal_request_template: Soc Rule Removal Request
task_scheduler_thread_pool_size: 10