server:
  port: 3333
spring:
  application:
    name: algosec-integration-ms
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
algosec-integration-ms:
  mss-datasource:
    username: portaluser
    password: PtW!%vDX.jo9+Ef
    jdbc-url: jdbc:mysql://dal09-dev-mssdb-01a:3306/mss
cleanup_threshold_hours: 24
network_protocol_list:
policy_update_request_template:
endpoints:
  allow: prometheus,health,info,actuator,swagger
error:
  code:
    unauthorized:
    forbidden:
    internal_error:
    bad_request:
    no_device_found:
    incorrect_device_count:
    no_algosec_enabled_device_found:
    no_algosec_actionable_work_found:
    no_algosec_ticket_details_found:
  message:
    unauthorized:
    forbidden:
    internal_error:
    bad_request:
    invalid_pcr_change_request_details:
    no_device_found:
    incorrect_device_count:
    no_algosec_enabled_device_found:
    no_algosec_actionable_work_found:
    invalid_policy_update_source:
    invalid_policy_update_destination:
    invalid_port:
    invalid_protocol:
    no_algosec_ticket_details_found:
  http_status:
    unauthorized:
    forbidden:
    internal_error:
    bad_request:
    no_device_found:
    incorrect_device_count:
    no_algosec_enabled_device_found:
    no_algosec_actionable_work_found:
    no_algosec_ticket_details_found:
app:
  service:
    url:
      algosec_fireflow_authentication_url: https://10.239.0.10/FireFlow/api/authentication/authenticate
      algosec_fireflow_change_request_url: https://10.239.0.10/FireFlow/api/change-requests/traffic
      device_enablement_values_url: https://dal09-dev-services.sec.ibm.com/micro/device_enablement_values?dataKey=AlgoSec+Log+Forwarding&status=Active&deviceId={0}
      device_url_with_hostname:
      algosec_fireflow_risk_report_url: https://10.239.0.10/FireFlow/REST/1.0/ticket
      device_mapping_url:
      find_network_objects_by_device_name:
      find_service_objects_by_device_name:
      algosec_traffic_simulation_url: https://10.239.0.10/afa/api/v1/query
algosec:
  ticket:
      status:
        close:
          field: Automation_status
          value: reject