server:
  port: 3333
spring:
  application:
    name: algosec-integration-ms
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
cleanup_threshold_hours: 24
network_protocol_list: TCP,UDP,ICMP,tcp,udp,icmp
policy_update_request_template: SOC Standard Request Template Test
policy_rule_removal_request_template: deleterule
object_update_rquest_template: Object Change Multi Device Request
risk_report_fetch_time_in_minute: 7
service_auth_token: d1daa7d55f076b0abcf40d5908f5ed84c475d9e7ab86e705f0f54c4e39f7b3c41f301a36ecdd6d5acc38ba90b42d01a29ab52e17a94cb98d9e1ff151248dbe81edce65bf9394d7dcf95cbb591bd1777b80bce4e83c4672bb2a1aadce8f038fe2260fd1238877e6f83446f3cfb6f450f9f2adef6109f352e3ea04fe6b7e594bf4
task_scheduler_thread_pool_size: 100
endpoints:
  allow: prometheus,health,info,actuator,swagger
error:
  code:
    unauthorized:
    forbidden:
    internal_error: 500
    bad_request:
    no_device_found:
    incorrect_device_count:
    no_algosec_enabled_device_found:
    no_algosec_actionable_work_found:
    no_algosec_ticket_details_found: 204
    no_algosec_change_needed_info_found: 204
  message:
    unauthorized:
    forbidden:
    internal_error: Internal Server Error
    bad_request:
    invalid_pcr_change_request_details:
    no_device_found:
    incorrect_device_count:
    no_algosec_enabled_device_found:
    no_algosec_actionable_work_found:
    invalid_policy_update_source:
    invalid_policy_update_destination:
    invalid_port:
    invalid_protocol:
    no_algosec_ticket_details_found:
    no_algosec_change_needed_info_found:
    risk_report_fetch_error: Unable to generate risk report 
  http_status:
    unauthorized:
    forbidden:
    internal_error: 500
    bad_request:
    no_device_found:
    incorrect_device_count:
    no_algosec_enabled_device_found:
    no_algosec_actionable_work_found:
    no_algosec_ticket_details_found: 204
    no_algosec_change_needed_info_found: 204
app:
  algosec:
    username: mss-ms
    password: Btk#cv@GkgVDU5Uu
  mss-datasource:
    username: portaluser
    password: PtW!%vDX.jo9+Ef
    jdbc-url: jdbc:mysql://dal09-dev-mssdb-01a.sec.ibm.com:3306/mss
  service:
    url:
      algosec_fireflow_authentication_url: https://atl-prd-algmgr-01.sec.ibm.com/FireFlow/api/authentication/authenticate
      algosec_fireflow_change_request_url: https://10.239.0.10/FireFlow/api/change-requests/traffic
      device_enablement_values_url: https://dal09-dev-services.sec.ibm.com/micro/device_enablement_values?dataKey=AlgoSec+Log+Forwarding&status=Active&deviceId={0}
      device_url_with_hostname: https://dal09-dev-services.sec.ibm.com/micro/device?hostName={0}&status=Active
      algosec_fireflow_risk_report_url: https://10.239.0.10/FireFlow/REST/1.0/ticket
      device_mapping_url:
      find_network_objects_by_device_name:
      find_service_objects_by_device_name:
      algosec_traffic_simulation_url: https://10.239.0.10/afa/api/v1/query
      device_url_with_algosec_unique_name: https://dal09-dev-services.sec.ibm.com/micro/device?algoSecUniqueName={0}
      algosec_device_mapping_urL: https://atl-prd-algmgr-01.sec.ibm.com/afa/api/v1/devices
      algosec_find_network_objects_by_device_name: https://10.239.0.10/afa/api/v1/networkObject/search/findByDeviceName?deviceNames={0}
      algosec_find_service_objects_by_remedy_device_id: https://10.239.0.10/afa/api/v1/network_services?entity={0}&size=1000
      algosec_fireflow_object_change_request_url: https://10.239.0.10/FireFlow/api/request/object
      algosec_rules_by_device_name_url: https://10.239.0.10/afa/api/v1/rule/{0}?ruleType=BASIC
      algosec_fireflow_rule_removal_request_url: https://10.239.0.10/FireFlow/api/change-requests/rule-removal
      
algosec:
  ticket:
      status:
        close:
          field: api_update
          value: rejected