apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: email-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: email-ms
  forceUpgrade: false
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: email-ms
    version: 1.0.22-master
  values:
    service:
      targetPort: 3333
    readinessProbe:
      initialDelaySeconds: 300
    livenessProbe:
      initialDelaySeconds: 300
    image:
      repository: mss-docker.artifactory.swg-devops.com/email-ms
      tag: 1.0.22-master.fe07e9f7
    nodeSelector:
      zone: yellow
    tolerations:
      - key: "zone"
        value: "yellow"
        effect: "NoExecute"
    replicaCount: 1
    imagePullSecrets:
    - name: docker-registry-pull
    resources:
      requests:
        cpu: .001
        memory: 128Mi
      limits:
        cpu: .5
        memory: 1G
    route:
      enabled: true
      host: email-ms.apps-pub.atl-prd-ocp-01.cl.sec.ibm.com
    secretsDir: "/vault/secrets"
    serviceAccount:
      create: true
    podAnnotations:
      vault.hashicorp.com/agent-inject: 'true'
      vault.hashicorp.com/role: email-ms
      vault.hashicorp.com/agent-inject-default-template: json
      vault.hashicorp.com/agent-inject-secret-newrelic.yml: "secret/modules/email-ms/newrelic"
      vault.hashicorp.com/agent-inject-template-newrelic.yml: |-
        {{ with secret "secret/modules/email-ms/newrelic" -}}
        common:
          agent_enabled: true
          app_name: email-ms-prd
          labels:
            Application: email-ms
            Namespace: Master
            Org: Lhs
            Region: Atl
            Stack: prd
          license_key: {{.Data.data.license_key}}
          log_file_name: STDOUT
          log_level: WARN
          send_data_on_exit: true
          send_data_on_exit_threshold: 60
          sync_startup: true
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-secrets.properties: secret/modules/email-ms/ms-properties
      vault.hashicorp.com/agent-inject-template-secrets.properties: |-
        {{- with secret "secret/modules/email-ms/ms-properties" -}}
        {{- range $key, $value := .Data.data -}}
        {{- printf "%s=%s\n" $key $value -}}
        {{- end -}}
        {{- end }}
    env:
      environment: prd
      spring_profiles_active: prd
      NEW_RELIC_LOG_FILE_NAME: STDOUT
      NEW_RELIC_LOG_LEVEL: WARN
      NEW_RELIC_SYNC_STARTUP: true
      NEW_RELIC_AGENT_ENABLED: true
      NEW_RELIC_SEND_DATA_ON_EXIT: true
      NEW_RELIC_SEND_DATA_ON_EXIT_THRESHOLD: 60
      NEW_RELIC_APP_NAME: email-ms-prd
      NEW_RELIC_LABELS: Application:email-ms;Org:Lhs;Region:Atl;Stack:Prd;Namespace:Master
      datasource.mail.url: jdbc:mysql://atl-prd-mssdb-01a.mss.iss.net:3306/mail?useSSL=true&requireSSL=true&verifyServerCertificate=false&useUnicode=yes&characterEncoding=UTF-8
      services.host.http.invoker.url: https://services.sec.ibm.com
      microservices.host.http.invoker.url: https://services.sec.ibm.com/micro
      MSS_LOCAL_PROPS: /vault/secrets/secrets.properties